//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.FitFlow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitFlowEntities : DbContext
    {
        public FitFlowEntities()
            : base("name=FitFlowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<GroupLeaderView> GroupLeaderView { get; set; }
        public virtual DbSet<GroupView> GroupView { get; set; }
        public virtual DbSet<UserView> UserView { get; set; }
        public virtual DbSet<Belongs> Belongs { get; set; }
    }
}
