//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.FitFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnCompletedTask
    {
        public string ProcessInstanceId { get; set; }
        public string TaskId { get; set; }
        public string TaskDefinitionKey { get; set; }
        public string TaskName { get; set; }
        public string TaskAssignee { get; set; }
        public string TaskAssigneeName { get; set; }
    }
}
