//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.FitFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Departments = new HashSet<Departments>();
            this.Departments1 = new HashSet<Departments>();
            this.Menus = new HashSet<Menus>();
            this.Menus1 = new HashSet<Menus>();
            this.Belongs = new HashSet<Belongs>();
            this.Belongs1 = new HashSet<Belongs>();
            this.Belongs2 = new HashSet<Belongs>();
        }
    
        public string Id { get; set; }
        public string Password { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Constants.DeleteFlg DeleteFlg { get; set; }
    
        public virtual ICollection<Departments> Departments { get; set; }
        public virtual ICollection<Departments> Departments1 { get; set; }
        public virtual ICollection<Menus> Menus { get; set; }
        public virtual ICollection<Menus> Menus1 { get; set; }
        public virtual ICollection<Belongs> Belongs { get; set; }
        public virtual ICollection<Belongs> Belongs1 { get; set; }
        public virtual ICollection<Belongs> Belongs2 { get; set; }
    }
}
