//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_ATTACHMENT
    {
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string USER_ID_ { get; set; }
        public string NAME_ { get; set; }
        public string DESCRIPTION_ { get; set; }
        public string TYPE_ { get; set; }
        public string TASK_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string URL_ { get; set; }
        public string CONTENT_ID_ { get; set; }
    }
}
