//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RU_TASK
    {
        public ACT_RU_TASK()
        {
            this.ACT_RU_IDENTITYLINK = new HashSet<ACT_RU_IDENTITYLINK>();
        }
    
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string NAME_ { get; set; }
        public string PARENT_TASK_ID_ { get; set; }
        public string DESCRIPTION_ { get; set; }
        public string TASK_DEF_KEY_ { get; set; }
        public string OWNER_ { get; set; }
        public string ASSIGNEE_ { get; set; }
        public string DELEGATION_ { get; set; }
        public Nullable<int> PRIORITY_ { get; set; }
        public Nullable<System.DateTime> CREATE_TIME_ { get; set; }
        public Nullable<System.DateTime> DUE_DATE_ { get; set; }
        public string CATEGORY_ { get; set; }
        public Nullable<int> SUSPENSION_STATE_ { get; set; }
        public string TENANT_ID_ { get; set; }
    
        public virtual ACT_RE_PROCDEF ACT_RE_PROCDEF { get; set; }
        public virtual ACT_RU_EXECUTION ACT_RU_EXECUTION { get; set; }
        public virtual ACT_RU_EXECUTION ACT_RU_EXECUTION1 { get; set; }
        public virtual ICollection<ACT_RU_IDENTITYLINK> ACT_RU_IDENTITYLINK { get; set; }
    }
}
