//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_PROCINST
    {
        public string ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string BUSINESS_KEY_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public System.DateTime START_TIME_ { get; set; }
        public Nullable<System.DateTime> END_TIME_ { get; set; }
        public Nullable<decimal> DURATION_ { get; set; }
        public string START_USER_ID_ { get; set; }
        public string START_ACT_ID_ { get; set; }
        public string END_ACT_ID_ { get; set; }
        public string SUPER_PROCESS_INSTANCE_ID_ { get; set; }
        public string DELETE_REASON_ { get; set; }
        public string TENANT_ID_ { get; set; }
    }
}
