//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_GE_BYTEARRAY
    {
        public ACT_GE_BYTEARRAY()
        {
            this.ACT_RU_JOB = new HashSet<ACT_RU_JOB>();
            this.ACT_RE_MODEL = new HashSet<ACT_RE_MODEL>();
            this.ACT_RE_MODEL1 = new HashSet<ACT_RE_MODEL>();
            this.ACT_RU_VARIABLE = new HashSet<ACT_RU_VARIABLE>();
        }
    
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string NAME_ { get; set; }
        public string DEPLOYMENT_ID_ { get; set; }
        public byte[] BYTES_ { get; set; }
        public Nullable<byte> GENERATED_ { get; set; }
    
        public virtual ACT_RE_DEPLOYMENT ACT_RE_DEPLOYMENT { get; set; }
        public virtual ICollection<ACT_RU_JOB> ACT_RU_JOB { get; set; }
        public virtual ICollection<ACT_RE_MODEL> ACT_RE_MODEL { get; set; }
        public virtual ICollection<ACT_RE_MODEL> ACT_RE_MODEL1 { get; set; }
        public virtual ICollection<ACT_RU_VARIABLE> ACT_RU_VARIABLE { get; set; }
    }
}
