//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RE_DEPLOYMENT
    {
        public ACT_RE_DEPLOYMENT()
        {
            this.ACT_GE_BYTEARRAY = new HashSet<ACT_GE_BYTEARRAY>();
            this.ACT_RE_MODEL = new HashSet<ACT_RE_MODEL>();
        }
    
        public string ID_ { get; set; }
        public string NAME_ { get; set; }
        public string CATEGORY_ { get; set; }
        public string TENANT_ID_ { get; set; }
        public Nullable<System.DateTime> DEPLOY_TIME_ { get; set; }
    
        public virtual ICollection<ACT_GE_BYTEARRAY> ACT_GE_BYTEARRAY { get; set; }
        public virtual ICollection<ACT_RE_MODEL> ACT_RE_MODEL { get; set; }
    }
}
