//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_TASKINST
    {
        public string ID_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string TASK_DEF_KEY_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string NAME_ { get; set; }
        public string PARENT_TASK_ID_ { get; set; }
        public string DESCRIPTION_ { get; set; }
        public string OWNER_ { get; set; }
        public string ASSIGNEE_ { get; set; }
        public System.DateTime START_TIME_ { get; set; }
        public Nullable<System.DateTime> CLAIM_TIME_ { get; set; }
        public Nullable<System.DateTime> END_TIME_ { get; set; }
        public Nullable<decimal> DURATION_ { get; set; }
        public string DELETE_REASON_ { get; set; }
        public Nullable<int> PRIORITY_ { get; set; }
        public Nullable<System.DateTime> DUE_DATE_ { get; set; }
        public string FORM_KEY_ { get; set; }
        public string CATEGORY_ { get; set; }
        public string TENANT_ID_ { get; set; }
    }
}
