//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_COMMENT
    {
        public string ID_ { get; set; }
        public string TYPE_ { get; set; }
        public System.DateTime TIME_ { get; set; }
        public string USER_ID_ { get; set; }
        public string TASK_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string ACTION_ { get; set; }
        public string MESSAGE_ { get; set; }
        public byte[] FULL_MSG_ { get; set; }
    }
}
