//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RU_EVENT_SUBSCR
    {
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string EVENT_TYPE_ { get; set; }
        public string EVENT_NAME_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string ACTIVITY_ID_ { get; set; }
        public string CONFIGURATION_ { get; set; }
        public System.DateTime CREATED_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string TENANT_ID_ { get; set; }
    
        public virtual ACT_RU_EXECUTION ACT_RU_EXECUTION { get; set; }
    }
}
