//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RU_EXECUTION
    {
        public ACT_RU_EXECUTION()
        {
            this.ACT_RU_EVENT_SUBSCR = new HashSet<ACT_RU_EVENT_SUBSCR>();
            this.ACT_RU_EXECUTION1 = new HashSet<ACT_RU_EXECUTION>();
            this.ACT_RU_EXECUTION11 = new HashSet<ACT_RU_EXECUTION>();
            this.ACT_RU_IDENTITYLINK = new HashSet<ACT_RU_IDENTITYLINK>();
            this.ACT_RU_TASK = new HashSet<ACT_RU_TASK>();
            this.ACT_RU_TASK1 = new HashSet<ACT_RU_TASK>();
            this.ACT_RU_VARIABLE = new HashSet<ACT_RU_VARIABLE>();
            this.ACT_RU_VARIABLE1 = new HashSet<ACT_RU_VARIABLE>();
        }
    
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string BUSINESS_KEY_ { get; set; }
        public string PARENT_ID_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string SUPER_EXEC_ { get; set; }
        public string ACT_ID_ { get; set; }
        public Nullable<byte> IS_ACTIVE_ { get; set; }
        public Nullable<byte> IS_CONCURRENT_ { get; set; }
        public Nullable<byte> IS_SCOPE_ { get; set; }
        public Nullable<byte> IS_EVENT_SCOPE_ { get; set; }
        public Nullable<byte> SUSPENSION_STATE_ { get; set; }
        public Nullable<int> CACHED_ENT_STATE_ { get; set; }
        public string TENANT_ID_ { get; set; }
    
        public virtual ACT_RE_PROCDEF ACT_RE_PROCDEF { get; set; }
        public virtual ICollection<ACT_RU_EVENT_SUBSCR> ACT_RU_EVENT_SUBSCR { get; set; }
        public virtual ICollection<ACT_RU_EXECUTION> ACT_RU_EXECUTION1 { get; set; }
        public virtual ACT_RU_EXECUTION ACT_RU_EXECUTION2 { get; set; }
        public virtual ICollection<ACT_RU_EXECUTION> ACT_RU_EXECUTION11 { get; set; }
        public virtual ACT_RU_EXECUTION ACT_RU_EXECUTION3 { get; set; }
        public virtual ICollection<ACT_RU_IDENTITYLINK> ACT_RU_IDENTITYLINK { get; set; }
        public virtual ICollection<ACT_RU_TASK> ACT_RU_TASK { get; set; }
        public virtual ICollection<ACT_RU_TASK> ACT_RU_TASK1 { get; set; }
        public virtual ICollection<ACT_RU_VARIABLE> ACT_RU_VARIABLE { get; set; }
        public virtual ICollection<ACT_RU_VARIABLE> ACT_RU_VARIABLE1 { get; set; }
    }
}
