//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_VARINST
    {
        public string ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string TASK_ID_ { get; set; }
        public string NAME_ { get; set; }
        public string VAR_TYPE_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string BYTEARRAY_ID_ { get; set; }
        public Nullable<double> DOUBLE_ { get; set; }
        public Nullable<decimal> LONG_ { get; set; }
        public string TEXT_ { get; set; }
        public string TEXT2_ { get; set; }
        public Nullable<System.DateTime> CREATE_TIME_ { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TIME_ { get; set; }
    }
}
