//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RE_MODEL
    {
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string NAME_ { get; set; }
        public string KEY_ { get; set; }
        public string CATEGORY_ { get; set; }
        public Nullable<System.DateTime> CREATE_TIME_ { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_TIME_ { get; set; }
        public Nullable<int> VERSION_ { get; set; }
        public string META_INFO_ { get; set; }
        public string DEPLOYMENT_ID_ { get; set; }
        public string EDITOR_SOURCE_VALUE_ID_ { get; set; }
        public string EDITOR_SOURCE_EXTRA_VALUE_ID_ { get; set; }
        public string TENANT_ID_ { get; set; }
    
        public virtual ACT_GE_BYTEARRAY ACT_GE_BYTEARRAY { get; set; }
        public virtual ACT_GE_BYTEARRAY ACT_GE_BYTEARRAY1 { get; set; }
        public virtual ACT_RE_DEPLOYMENT ACT_RE_DEPLOYMENT { get; set; }
    }
}
