//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_ID_GROUP
    {
        public ACT_ID_GROUP()
        {
            this.ACT_ID_USER = new HashSet<ACT_ID_USER>();
        }
    
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string NAME_ { get; set; }
        public string TYPE_ { get; set; }
    
        public virtual ICollection<ACT_ID_USER> ACT_ID_USER { get; set; }
    }
}
