//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitFlow.Models.Activiti
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivitiEntities : DbContext
    {
        public ActivitiEntities()
            : base("name=ActivitiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACT_GE_BYTEARRAY> ACT_GE_BYTEARRAY { get; set; }
        public virtual DbSet<ACT_GE_PROPERTY> ACT_GE_PROPERTY { get; set; }
        public virtual DbSet<ACT_HI_ACTINST> ACT_HI_ACTINST { get; set; }
        public virtual DbSet<ACT_HI_ATTACHMENT> ACT_HI_ATTACHMENT { get; set; }
        public virtual DbSet<ACT_HI_COMMENT> ACT_HI_COMMENT { get; set; }
        public virtual DbSet<ACT_HI_DETAIL> ACT_HI_DETAIL { get; set; }
        public virtual DbSet<ACT_HI_IDENTITYLINK> ACT_HI_IDENTITYLINK { get; set; }
        public virtual DbSet<ACT_HI_PROCINST> ACT_HI_PROCINST { get; set; }
        public virtual DbSet<ACT_HI_TASKINST> ACT_HI_TASKINST { get; set; }
        public virtual DbSet<ACT_HI_VARINST> ACT_HI_VARINST { get; set; }
        public virtual DbSet<ACT_ID_GROUP> ACT_ID_GROUP { get; set; }
        public virtual DbSet<ACT_ID_INFO> ACT_ID_INFO { get; set; }
        public virtual DbSet<ACT_ID_USER> ACT_ID_USER { get; set; }
        public virtual DbSet<ACT_RE_DEPLOYMENT> ACT_RE_DEPLOYMENT { get; set; }
        public virtual DbSet<ACT_RE_MODEL> ACT_RE_MODEL { get; set; }
        public virtual DbSet<ACT_RE_PROCDEF> ACT_RE_PROCDEF { get; set; }
        public virtual DbSet<ACT_RU_EVENT_SUBSCR> ACT_RU_EVENT_SUBSCR { get; set; }
        public virtual DbSet<ACT_RU_EXECUTION> ACT_RU_EXECUTION { get; set; }
        public virtual DbSet<ACT_RU_IDENTITYLINK> ACT_RU_IDENTITYLINK { get; set; }
        public virtual DbSet<ACT_RU_JOB> ACT_RU_JOB { get; set; }
        public virtual DbSet<ACT_RU_TASK> ACT_RU_TASK { get; set; }
        public virtual DbSet<ACT_RU_VARIABLE> ACT_RU_VARIABLE { get; set; }
    }
}
